### ISSUE TITLE
Outputs not working correctly on current Node-Red

### ISSUE THREAD

**Issue by Admiraldr** [nobodyMO/node-red-contrib-piface-digital#4]
I installed node-red-contrib-piface-digital on a new RaspberryPiOS (Bullseye) on the most recent Node Red (3.0.2) .
All the Outputs work fine as far as I can see.

There is an issue with the inputs: If I press the first button, all 4 Inputs go on and stay on.
Pressing the other buttons has no effect. 

Testing the input buttons from commandline with python (presslights.py from pifacedigitalio) works fine, so I guess it's not the hardware.

**Comment by nobodyMO** [comment]
Thank you for reporting the defect. Unfortunately, I cannot reproduce it myself, as I do not own a piface. I developed the node a few years ago for someone else on the iobroker forum. 

As far as I can see from the error description, the error is not in the node-red node itself, but in the underlying library. 

The library is https://github.com/tualo/node-pifacedigital. When installing the node-red-node, the latest version of this library is automatically installed by npm. 

The following defect exists for this library, which should correspond to this error:
https://github.com/tualo/node-pifacedigital/issues/11

If the error is corrected there, this node should also work correctly again.

**Comment by Admiraldr** [comment]
Thanks for the answer. 

Yes, this is exactly the behaviour I am experiencing. I will try to follow up with the defect in the other library.
